
/**
 * Author:  Federico
 * Created: 9-mag-2017
 */

/** Dati accesso DB
*   username: 'username'
*   password: 'password'
*/

CREATE TABLE postType (
    postType_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(32)
);

CREATE TABLE utente (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    dataNascita date,   
    frasePresentazione VARCHAR(256),
    email VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    urlFotoProfilo VARCHAR(256)
);

CREATE TABLE gruppo (
    gruppo_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    frasePresentazione VARCHAR(256),
    urlFotoProfilo VARCHAR(256),
    amministratore INTEGER,
    FOREIGN KEY (amministratore) REFERENCES utente(utente_id)
);

CREATE TABLE post (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore INTEGER,
    FOREIGN KEY (autore) REFERENCES utente(utente_id),
    text VARCHAR(1024),
    content VARCHAR(1024),
    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES postType(postType_id),
    groupDest INTEGER,
    FOREIGN KEY (groupDest) REFERENCES gruppo(gruppo_id),
    utenteDest INTEGER,
    FOREIGN KEY (utenteDest) REFERENCES utente(utente_id)
);



CREATE TABLE amicizie (
   follower INTEGER,
   FOREIGN KEY (follower) REFERENCES utente(utente_id),
   followed INTEGER,
   FOREIGN KEY (followed) REFERENCES utente(utente_id),
   PRIMARY KEY (follower, followed)
);

--Popolamento tabella utente

INSERT INTO utente (utente_id, nome, cognome,  dataNascita, frasePresentazione, email, password, urlfotoprofilo)
VALUES (default,
        'Andonio',
        'Cipolla',
        '1980-02-16',
        'Non c è niente di meglio che un piatto di pasta con fagioli',
        'utente1@gmail.com',
        '123',
        'img/utente1.jpg');

INSERT INTO utente (utente_id, nome, cognome,  dataNascita, frasePresentazione, email, password, urlfotoprofilo)
VALUES (default,
        'Djanni',
        'Tocco',
        '2010-05-10',
        '',
        'djannigatto@gmail.com',
        '123',
        'img/utente2.jpg');

INSERT INTO utente (utente_id, nome, cognome,  dataNascita, frasePresentazione, email, password, urlfotoprofilo)
VALUES (default,
        'Javier',
        'Zanetti',
        '1973-08-10',
        'FOZZA INDA',
        'utente3@gmail.com',
        '123',
        'img/utente3.jpg');

--Popolamento tabella postType

INSERT INTO postType (postType_id, nome)
VALUES (default, 'TEXT');

INSERT INTO postType (postType_id, nome)
VALUES (default, 'IMAGE');

INSERT INTO postType (postType_id, nome)
VALUES (default, 'LINK');

--Popolamento tabella post

INSERT INTO post (post_id, autore, text, content, tipo, groupDest, utenteDest)
VALUES (default,
        1,
        'Per me è la cipolla',
        null,
        1,
        null,
        1);

INSERT INTO post (post_id, autore, text, content, tipo, groupDest, utenteDest)
VALUES (default,
        1,
        'Passa parola',
        null,
        1,
        null,
        1);

INSERT INTO post (post_id, autore, text, content, tipo, groupDest, utenteDest)
VALUES (default,
        2,
        'Madò che bell stu gatt',
        'img/djanni1.jpg',
        2,
        null,
        2);

INSERT INTO post (post_id, autore, text, content, tipo, groupDest, utenteDest)
VALUES (default,
        2,
        'Quanti like merito?',
        'img/djanni2.jpg',
        2,
        null,
        2);

INSERT INTO post (post_id, autore, text, content, tipo, groupDest, utenteDest)
VALUES (default,
        3,
        'Giusto per non dimenticare..',
        'https://www.google.it/search?q=triplete+inter&rlz=1C1CHZL_itIT679IT679&tbm=isch&imgil=GEoyxK5Ind0YGM%253A%253BxoYtDPzqhM-SrM%253Bhttp%25253A%25252F%25252Fwww.memegen.it%25252Fmemes%25252Ftriplete_inter&source=iu&pf=m&fir=GEoyxK5Ind0YGM%253A%252CxoYtDPzqhM-SrM%252C_&usg=__Ybez3OkdsvPJ0BVonbAXsUnHp4c%3D&biw=1366&bih=662&ved=0ahUKEwjDmoz47tXSAhXLuhoKHQsEC8wQyjcILQ&ei=ntDHWMPTEMv1aouIrOAM#imgrc=GEoyxK5Ind0YGM:',
        3,
        null,
        3);

--Popolamento tabella Hearts (relativa alle amicizie)
INSERT INTO amicizie (follower, followed)
VALUES (1, 2),
       (1, 3),
       (2, 1),
       (2, 3);

INSERT INTO amicizie (follower, followed)
VALUES (3, 1),
       (3, 2);

INSERT INTO gruppo (gruppo_id, nome, frasePresentazione, urlFotoProfilo, amministratore)
VALUES (default,
        'Clash of clans',
        'Solo per utenti pro!',
        'img/gruppo1.jpg',
        1);

INSERT INTO gruppo (gruppo_id, nome, frasePresentazione, urlFotoProfilo, amministratore)
VALUES (default,
        'Interisti per sempre',
        '#AMALA!',
        'img/gruppo2.jpg',
        3);
